<?php
/**
 * @file webform_gdpr.module
 * 
 * Module hooks and callbacks.
 */

/**
 * Implements hook_module_implements_alter().
 */
function webform_gdpr_module_implements_alter(&$implementations, $hook) {
  $k = 'webform_gdpr';
  if ( $hook == 'form_alter' ) {
    // Ensure form_alter hook implementation is invoked after webform_civicrm.
    if( isset($implementations[$k]) ) {
      $group = $implementations[$k];
      unset($implementations[$k]);
      $implementations[$k] = $group;
    }
  }
}

/**
 * Implements hook_webform_component_info()
 */
function webform_gdpr_webform_component_info() {
  $components = array();

  $components['gdpr'] = array(
    'label' => t('GDPR'),
    'description' => t('Terms & Conditions / Data Policy'),
    'file' => 'includes/webform_gdpr_component.inc',
    'value' => 1,
    'conditional_type' => 'select',
    'features' => array(
      'analysis' => FALSE,
      'csv' => FALSE,
      'default_value' => FALSE,
      'description' => TRUE,
      'email' => TRUE,
      'email_address' => 'FALSE',
      'email_name' => FALSE,
      'required' => TRUE,
      'title' => TRUE,
      'title_display' => TRUE,
      'title_inline' => TRUE,
    ),
  );
  $components['gdpr_comms_prefs'] = array(
    'label' => t('GDPR Comms Prefs'),
    'description' => t('Communications Preferences'),
    'file' => 'includes/webform_gdpr_comms_prefs_component.inc',
    'value' => 1,
    'features' => array(
      'analysis' => FALSE,
      'csv' => FALSE,
      'default_value' => FALSE,
      'description' => TRUE,
      'email' => TRUE,
      'email_address' => 'FALSE',
      'email_name' => FALSE,
      'required' => TRUE,
      'title' => TRUE,
      'title_display' => TRUE,
      'title_inline' => TRUE,
    ),
  );
  return $components;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for a webform_client_form.
 */
function webform_gdpr_form_webform_client_form_alter(&$form, &$form_state) {
  if ($components = webform_gdpr_get_components($form['#node'])) {
    $form['#submit'][] = 'webform_gdpr_submit';
    $form['#attached']['js'][] = drupal_get_path('module', 'webform_gdpr') . '/js/webform_gdpr.js';
   }
}

/**
 * 
 */
function webform_gdpr_validate_gdpr($element, &$form_state) {
  if (empty($element['#value']) && $element['#required'] ) {
    $msg = t("Please check %name.", array('%name' => strip_tags($element['#title'])));
    form_error($element, $msg);
    
  }
}

/**
 * Validation callback function for Comms Prefs element.
 * 
 */
function webform_gdpr_validate_comms_prefs($element, &$form_state) {
  // Which groups have been selected.
  if (empty($element['groups'])) {
    return;
  }
  $selected_channels = [];
  foreach (element_children($element['channels']) as $key) {
    $elem = $element['channels'][$key];
    if ($elem['#value'] == 'YES') {
      $selected_channels[] = $key;
    }
  }
  foreach (element_children($element['groups']) as $key) {
    // If the group is selected then at least one of it's channels
    // should also be selected.
    $elem = $element['groups'][$key];
    if (!empty($elem['#value'])) {
      $channels = $elem['#channels'];
      if ($channels && empty(array_intersect($channels, $selected_channels))) {
        $msg = t('You have selected @group but have opted out of all the channels that it uses.', array(
          '@group' => $elem['#title'],
        ));   
        form_error($elem, $msg);
      }
    }
  }
}

/**
 * Submit callback for webform.
 */
function webform_gdpr_submit(&$form, &$form_state) {
  if (!empty($form_state['save_draft']) || empty($form_state['webform_completed'])) {
    return;
  }
  $components = webform_gdpr_get_components($form['#node'], 'gdpr');
  $comms_prefs_components = webform_gdpr_get_components($form['#node'], 'gdpr_comms_prefs');
  if (!$components || !$comms_prefs_components) {
    return;
  }

  // Load the created submission to get contacts.
  $sid = !empty($form_state['values']['details']['sid']) ? $form_state['values']['details']['sid'] : NULL;
  $nid = !empty($form['#node']->nid) ? $form['#node']->nid : NULL;
  if ($sid && $nid) {
    $submission = webform_get_submission($nid, $sid);
  }
  if (empty($submission->civicrm['contact'])) {
    return;
  }
  $contacts = $submission->civicrm['contact'];
  // Handle gdpr components. 
  foreach ($components as $cid => $component) {
    if (!empty($submission->data[$cid])) {
      $contact_idx = $component['extra']['contact'];
      $contact_id = !empty($contacts[$contact_idx]['id']) ? $contacts[$contact_idx]['id'] : 0;
      if (!$contact_id) {
        continue;
      }
      if (!empty($component['extra']['enable_data_policy'])) {
        WebformGdpr::recordAcceptance($contact_id);
      }
      if (!empty($component['extra']['enable_tc_event'])) {
        WebformGdpr::recordAcceptance($contact_id, 'Event', $component['extra']['tc_event']);
      }
      if (!empty($component['extra']['enable_tc_contribution'])) {
        WebformGdpr::recordAcceptance($contact_id, 'ContributionPage', $component['extra']['tc_contribution']);
      }
    }
  }
  // Handle comms prefs components.
  foreach ($comms_prefs_components as $cid => $component) {
    $values = $submission->data[$cid];
    $values = $values[0];
    if (is_string($values)) {
      $values = unserialize($values);
    }
    $contact_id = $contacts[1]['id'];
    WebformGDPRCommsPrefs::processCommsPrefs($component, $values, $contact_id);    
  }
}

/**
 * Returns gdpr components for a webform.
 *
 * @param stdObject $node
 *   Webform node.
 * @param string $type
 *  Optional filter by component type.
 *   gdpr|gdpr_comms_prefs
 *
 * @return array
 *   Gdpr component definitions, keyed by component id.
 */
function webform_gdpr_get_components($node, $type = '') {
  $gdpr_components = [];
  $types = $type ? [$type] : ['gdpr', 'gdpr_comms_prefs'];
  if (!empty($node->webform['components'])) {
    foreach ($node->webform['components'] as $cid => $component) {
      if (in_array($component['type'], $types)) {
        $gdpr_components[$cid] = $component;
      }
    }
  }
  return $gdpr_components;
}
